extends: default

rules:
  # keep it friendly for GitHub Actions YAML
  line-length:
    max: 140
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy: disable                # allows "on: push" etc
  document-start: disable        # no need for '---' at file start
  comments-indentation: disable
  indentation:
    indent-sequences: consistent
    check-multi-line-strings: false