name: _deploy-aks-helm (template)
on:
  workflow_call:
    inputs:
      env_name:  { type: string, required: true }
      image_repo:{ type: string, required: true }
      image_tag: { type: string, required: true }
      chart_path:{ type: string, required: true }
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: az aks get-credentials -g $AKS_RG -n $AKS_NAME --overwrite-existing
      - uses: Azure/setup-helm@v4
      - run: |
          helm upgrade --install app ${{ inputs.chart_path }}             --set image.repository=${{ inputs.image_repo }}             --set image.tag=${{ inputs.image_tag }}
