name: Auto sync main → dev

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: auto-sync-main-to-dev
  cancel-in-progress: true

jobs:
  open-sync-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if dev is behind main
        id: compare
        uses: actions/github-script@v7
        with:
