name: Auto sync main → staging & dev

on:
  release:
    types: [published]          # When a GitHub Release is published
  push:
    tags: ["v*"]                # Or when a version tag is pushed
  workflow_dispatch: {}         # Manual run

permissions:
  contents: write               # push sync branches
  pull-requests: write          # open/update PRs

concurrency:
  group: auto-sync-main-to-branches
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [staging, dev]

    env:
      SYNC_BRANCH: sync/main-to-${{ matrix.target }}-${{ github.run_id }}

    steps:
      - name: Compare ${{ matrix.target }}…main
        id: cmp
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const r = await github.rest.repos.compareCommits({
              owner, repo, base: '${{ matrix.target }}', head: 'main'
            });
            core.setOutput('behind_by', String(r.data.behind_by));

      - name: Stop early if ${{ matrix.target }} is up to date
        if: steps.cmp.outputs.behind_by == '0'
        run: echo "${{ matrix.target }} is already up to date."

      - name: Checkout ${{ matrix.target }} (full history)
        if: steps.cmp.outputs.behind_by != '0'
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.target }}
          fetch-depth: 0

      - name: Configure git user
        if: steps.cmp.outputs.behind_by != '0'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create sync branch from ${{ matrix.target }}
        if: steps.cmp.outputs.behind_by != '0'
        run: |
          git fetch origin main ${{ matrix.target }}
          git switch -c "$SYNC_BRANCH" "origin/${{ matrix.target }}"

      - name: Merge main → ${{ matrix.target }} (keep target’s service-deploy.yml)
        if: steps.cmp.outputs.behind_by != '0'
        shell: bash
        run: |
          set -euxo pipefail
          if ! git merge --no-ff --no-edit origin/main; then
            git checkout --ours .github/workflows/service-deploy.yml || true
            git add .github/workflows/service-deploy.yml || true
            git commit -m "sync(main→${{ matrix.target }}): keep ${{ matrix.target }} copy of service-deploy.yml"
          fi
          git push -u origin "$SYNC_BRANCH"

      - name: Open or update PR (→ ${{ matrix.target }})
        if: steps.cmp.outputs.behind_by != '0'
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = process.env.SYNC_BRANCH;
            const base = '${{ matrix.target }}';

            const list = await github.rest.pulls.list({
              owner, repo, state: 'open', base, head: `${owner}:${head}`
            });

            let pr;
            if (list.data.length) {
              pr = list.data[0];
            } else {
              pr = (await github.rest.pulls.create({
                owner, repo,
                title: `chore(sync): main → ${base}`,
                base,
                head,
                body: [
                  `Automated sync of **main** back into **${base}** after release.`,
                  '',
                  '- Pre-resolved `.github/workflows/service-deploy.yml` to keep the target branch copy.',
                  '- Merge method: regular **merge** to preserve production SHAs.'
                ].join('\n')
              })).data;
            }
            core.setOutput('number', pr.number);
            core.notice(`Opened/updated PR #${pr.number} → ${base}`);

      # Dev can be auto-merged, staging should remain review-gated
      - name: Enable auto-merge (MERGE) for dev only
        if: matrix.target == 'dev' && steps.cmp.outputs.behind_by != '0'
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = Number("${{ steps.pr.outputs.number }}");
            const q = await github.graphql(
              `query($owner:String!,$repo:String!,$number:Int!){
                 repository(owner:$owner,name:$repo){
                   pullRequest(number:$number){ id }
                 }
               }`, { owner, repo, number }
            );
            const id = q.repository.pullRequest.id;
            await github.graphql(
              `mutation($id:ID!){
                 enablePullRequestAutoMerge(input:{
                   pullRequestId:$id, mergeMethod:MERGE
                 }) { clientMutationId }
               }`, { id }
            );