name: deploy-local

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy"
        required: false
        default: "latest"
      env_name:
        description: "Environment name"
        type: choice
        options: ["dev", "staging", "production"]
        required: true
        default: "dev"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/setup-helm@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy with Helm (dry-run)
        run: |
          helm upgrade --install demo-app deploy/chart \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/demo-app \
            --set image.tag=${{ inputs.image_tag }} \
            --set env.name=${{ inputs.env_name }} \
            --dry-run --debug