name: _deploy-aks-helm (template)

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
      image_repo:
        type: string
        required: true
      image_tag:
        type: string
        required: true
      chart_path:
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials -g "${AKS_RG}" -n "${AKS_NAME}" --overwrite-existing
        env:
          AKS_RG:   ${{ vars.AKS_RG }}
          AKS_NAME: ${{ vars.AKS_NAME }}

      - name: Setup Helm
        uses: Azure/setup-helm@v4

      - name: Helm upgrade/install
        run: >
          helm upgrade --install app "${{ inputs.chart_path }}"
          --set image.repository="${{ inputs.image_repo }}"
          --set image.tag="${{ inputs.image_tag }}"
          --set env.name="${{ inputs.env_name }}"