name: service-ci

on:
  pull_request:
    branches: ["dev", "staging", "main"]
<<<<<<< HEAD
  push:
    branches: ["dev", "staging", "main"]

=======

# deny-by-default; jobs escalate only if needed
>>>>>>> main
permissions:
  contents: read

concurrency:
  group: service-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    name: lint-yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Advisory lint (parsable)
        run: yamllint -f parsable .github/workflows
        continue-on-error: true
      - name: Strict syntax sanity
        run: |
          yamllint -f parsable \
<<<<<<< HEAD
            -d "{rules:{document-start: disable, line-length: disable, truthy: disable, comments: disable, indentation:{indent-sequences: consistent}}}" \
=======
            -d '{rules:{document-start: disable, line-length: disable, truthy: disable, comments: disable, indentation:{indent-sequences: consistent}}}' \
>>>>>>> main
            .github/workflows

  call-ci-template:
    # this job name will appear as: service-ci / call-ci-template / ci (pull_request)
    needs: lint-yaml
<<<<<<< HEAD
    uses: ./.github/workflows/_ci-node.yml
    permissions:
      contents: read
      packages: write
=======
    uses: namaimichael/oaf-gha-migration-skeleton/.github/workflows/ci-node.yml@main
    # example: if you need extra scopes during CI, uncomment below
    # permissions:
    #   packages: write
    #   security-events: write
    #   id-token: write
>>>>>>> main
