name: service-ci
on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Lint GitHub workflows
        run: yamllint .github/workflows
        continue-on-error: true

  call-ci-template:
    needs: lint-yaml
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    uses: namaimichael/oaf-gha-migration-skeleton/.github/workflows/ci-node.yml@main