name: service-deploy

on:
  push:
    branches: ["dev", "staging", "main"]
  workflow_dispatch:
    inputs:
      env_name:
        type: choice
        options: ["dev", "staging", "production"]
        default: "dev"
        required: true

permissions:
  contents: read

env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/demo-app
  CHART_PATH: deploy/chart

jobs:
  auto-deploy-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    concurrency:
      group: deploy-dev
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/setup-helm@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm upgrade (dry-run)
        run: |
          helm upgrade --install demo-app "${{ env.CHART_PATH }}" \
            --set image.repository="${{ env.IMAGE_REPO }}" \
            --set image.tag="${{ github.sha }}" \
            --set env.name=dev \
            --dry-run --debug

  auto-deploy-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    concurrency:
      group: deploy-staging
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/setup-helm@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm upgrade (dry-run)
        run: |
          helm upgrade --install demo-app "${{ env.CHART_PATH }}" \
            --set image.repository="${{ env.IMAGE_REPO }}" \
            --set image.tag="${{ github.sha }}" \
            --set env.name=staging \
            --dry-run --debug

  auto-deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    concurrency:
      group: deploy-production
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/setup-helm@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm upgrade (dry-run)
        run: |
          helm upgrade --install demo-app "${{ env.CHART_PATH }}" \
            --set image.repository="${{ env.IMAGE_REPO }}" \
            --set image.tag="${{ github.sha }}" \
            --set env.name=production \
            --dry-run --debug

  manual-deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/setup-helm@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm upgrade (dry-run)
        run: |
          helm upgrade --install demo-app "${{ env.CHART_PATH }}" \
            --set image.repository="${{ env.IMAGE_REPO }}" \
            --set image.tag="${{ github.sha }}" \
            --set env.name="${{ inputs.env_name }}" \
            --dry-run --debug