name: service-deploy
on:
  workflow_dispatch:
    inputs:
      env_name:
        type: choice
        options: [ "staging", "production" ]
        required: true
        default: "staging"
jobs:
  call-deploy-template:
    uses: ./.github/workflows/_templates/deploy-aks-helm.yml
    with:
      env_name: ${{ inputs.env_name }}
      image_repo: ${{ vars.ACR_NAME }}.azurecr.io/app
      image_tag: ${{ github.run_number }}
      chart_path: deploy/chart
