name: service-ci

on:
  pull_request:
    branches: ["dev", "staging", "main"]

# deny-by-default; jobs escalate only if needed
permissions:
  contents: read

concurrency:
  group: service-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    name: lint-yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Advisory lint (parsable)
        run: yamllint -f parsable .github/workflows
        continue-on-error: true
      - name: Strict syntax sanity
        run: |
          yamllint -f parsable \
            -d '{rules:{document-start: disable, line-length: disable, truthy: disable, comments: disable, indentation:{indent-sequences: consistent}}}' \
            .github/workflows

  call-ci-template:
    needs: lint-yaml
    uses: namaimichael/oaf-gha-migration-skeleton/.github/workflows/ci-node.yml@main
    permissions:               # 👈 match what the reusable job requests
      contents: read
      packages: write
      id-token: write
      security-events: write